services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/apps
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    env_file:
      - .env
