services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/apps
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis:16-3.4
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    env_file:
      - .env

  redis:
    image: redis:7.4.3
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/redis_data