# Generated by Django 5.1.5 on 2025-02-15 16:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("here_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SportEstablishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("here_id", models.CharField(max_length=255)),
                ("address_label", models.CharField(max_length=255)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("working_hours", models.DateTimeField(blank=True, null=True)),
                ("working_days", models.DateField(blank=True, null=True)),
                ("telephone_number", models.CharField(max_length=255)),
                ("site", models.CharField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("categories", models.ManyToManyField(to="map.category")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="map.city"
                    ),
                ),
            ],
        ),
    ]
