# Generated by Django 5.1.5 on 2025-02-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sportestablishment",
            name="working_days",
        ),
        migrations.RemoveField(
            model_name="sportestablishment",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="sportestablishment",
            name="weekly_schedule",
            field=models.CharField(blank=True, null=True),
        ),
    ]
