# Generated by Django 5.1.5 on 2025-02-19 19:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_remove_sportestablishment_working_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListedArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("radius", models.IntegerField(default=10000)),
                (
                    "annotation",
                    models.TextField(help_text="Reason to add coordinates in model"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
